{
    parserClass="xyz.janek.simplates.language.parser.SimplatesParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
    psiClassPrefix="Simplates"
    psiImplClassSuffix="Impl"
    psiPackage="xyz.janek.simplates.language.psi.impl"

    elementTypeHolderClass="xyz.janek.simplates.language.psi.SimplatesTypes"
    elementTypeClass="xyz.janek.simplates.language.psi.SimplatesElementType"
    tokenTypeClass="xyz.janek.simplates.language.psi.SimplatesTokenType"

    tokens=[
        BEGIN='regexp:\[---+]'
        CONTENT_TYPE='regexp:[a-z]+/[a-z.+\-]+'
        FUNCTION_NAME='regexp:[a-zA-Z_][a-z0-9_]+'
        CODE='regexp:.*'
        SEP_SPACE='regexp:\s+'
        VIA_TOKEN='regexp:(via)'
    ]
}

simplatesFile ::= item_*

private item_ ::= (annotation|CODE)

annotation ::= BEGIN [SEP_SPACE content_]
private content_ ::= CONTENT_TYPE [SEP_SPACE via_]
private via_ ::= VIA_TOKEN SEP_SPACE FUNCTION_NAME